# Generated by Django 4.2.1 on 2026-07-23 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAdministrativa',
            fields=[
                ('id_area_administrativa', models.IntegerField(db_column='ID_AREA_ADMINISTRATIVA', primary_key=True, serialize=False)),
                ('nombre_area_administrativa', models.CharField(db_column='NOMBRE_AREA_ADMINISTRATIVA', max_length=70, null=True)),
            ],
            options={
                'db_table': 'AREA_ADMINISTRATIVA',
            },
        ),
        migrations.CreateModel(
            name='Autentificacion',
            fields=[
                ('id_autentificacion', models.BigAutoField(db_column='ID_AUTENTIFICACION', primary_key=True, serialize=False)),
                ('codigo_autentificacion', models.BinaryField(db_column='CODIGO_AUTENTIFICACION', max_length=32, null=True)),
                ('fecha_autentificacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_AUTENTIFICACION')),
            ],
            options={
                'db_table': 'AUTENTIFICACION',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(db_column='ID_COMUNA', primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(db_column='NOMBRE_COMUNA', max_length=60, null=True)),
            ],
            options={
                'db_table': 'COMUNA',
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id_conversacion', models.BigAutoField(db_column='ID_CONVERSACION', primary_key=True, serialize=False)),
                ('nombre_conversacion', models.CharField(db_column='NOMBRE_CONVERSACION', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_CREACION')),
            ],
            options={
                'db_table': 'CONVERSACION',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.BigAutoField(db_column='ID_DOCUMENTO', primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(db_column='NOMBRE_DOCUMENTO', max_length=60, null=True)),
                ('archivo', models.BinaryField(db_column='ARCHIVO', null=True)),
                ('fecha_subida_documento', models.DateTimeField(auto_now_add=True, db_column='FECHA_SUBIDA_DOCUMENTO')),
            ],
            options={
                'db_table': 'DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='EstadoAutentificacion',
            fields=[
                ('id_estado_autentificacion', models.IntegerField(db_column='ID_ESTADO_AUTENTIFICACION', primary_key=True, serialize=False)),
                ('nombre_estado_autentificacion', models.CharField(db_column='NOMBRE_ESTADO_AUTENTIFICACION', max_length=40, null=True)),
            ],
            options={
                'db_table': 'ESTADO_AUTENTIFICACION',
            },
        ),
        migrations.CreateModel(
            name='EstadoConsulta',
            fields=[
                ('id_estado_consulta', models.IntegerField(db_column='ID_ESTADO_CONSULTA', primary_key=True, serialize=False)),
                ('nombre_estado_consulta', models.CharField(db_column='NOMBRE_ESTADO_CONSULTA', max_length=30, null=True)),
            ],
            options={
                'db_table': 'ESTADO_CONSULTA',
            },
        ),
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('id_estado_documento', models.IntegerField(db_column='ID_ESTADO_DOCUMENTO', primary_key=True, serialize=False)),
                ('nombre_estado_documento', models.CharField(db_column='NOMBRE_ESTADO_DOCUMENTO', max_length=40, null=True)),
            ],
            options={
                'db_table': 'ESTADO_DOCUMENTO',
            },
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id_publicacion', models.BigAutoField(db_column='ID_PUBLICACION', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='TITULO', max_length=255, null=True)),
                ('sub_titulo', models.CharField(blank=True, db_column='SUB_TITULO', max_length=255, null=True)),
                ('descripcion_publicacion', models.TextField(db_column='DESCRIPCION_PUBLICACION', null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_PUBLICACION')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='ACTUALIZADO_EN')),
                ('estado_moderacion', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], db_column='ESTADO_MODERACION', default='PENDIENTE', max_length=10)),
            ],
            options={
                'db_table': 'PUBLICACIONES',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(db_column='ID_REGION', primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(db_column='NOMBRE_REGION', max_length=40, null=True)),
            ],
            options={
                'db_table': 'REGION',
            },
        ),
        migrations.CreateModel(
            name='RolCuentaAdministrativa',
            fields=[
                ('id_rol_cuenta_administrativa', models.IntegerField(db_column='ID_ROL_CUENTA_ADMINISTRATIVA', primary_key=True, serialize=False)),
                ('nombre_rol_cuenta_administrativa', models.CharField(db_column='NOMBRE_ROL_CUENTA_ADMINISTRATIVA', max_length=60, null=True)),
            ],
            options={
                'db_table': 'ROL_CUENTA_ADMINISTRATIVA',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id_tipo_cuenta', models.IntegerField(db_column='ID_TIPO_CUENTA', primary_key=True, serialize=False)),
                ('nombre_tipo_cuenta', models.CharField(db_column='NOMBRE_TIPO_CUENTA', max_length=50, null=True)),
                ('valor_cuenta', models.IntegerField(db_column='VALOR_CUENTA', null=True)),
            ],
            options={
                'db_table': 'TIPO_CUENTA',
            },
        ),
        migrations.CreateModel(
            name='TipoFirma',
            fields=[
                ('id_tipo_firma', models.IntegerField(db_column='ID_TIPO_FIRMA', primary_key=True, serialize=False)),
                ('nombre_tipo_firma', models.CharField(db_column='NOMBRE_TIPO_FIRMA', max_length=40, null=True)),
            ],
            options={
                'db_table': 'TIPO_FIRMA',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.BigAutoField(db_column='ID_TRANSACCION', primary_key=True, serialize=False)),
                ('tiempo_transaccion', models.DateTimeField(auto_now_add=True, db_column='TIEMPO_TRANSACCION')),
                ('tipo_cuenta', models.ForeignKey(db_column='FK_VALOR_CUENTA', null=True, on_delete=django.db.models.deletion.PROTECT, to='KeyServApp.tipocuenta')),
            ],
            options={
                'db_table': 'TRANSACCION',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('rut_usuario', models.CharField(db_column='RUT_USUARIO', max_length=10, null=True)),
                ('nombre_usuario', models.CharField(db_column='NOMBRE_USUARIO', max_length=40, null=True)),
                ('nombre2_usuario', models.CharField(blank=True, db_column='NOMBRE2_USUARIO', max_length=40, null=True)),
                ('apellido_usuario', models.CharField(db_column='APELLIDO_USUARIO', max_length=40, null=True)),
                ('apellido2_usuario', models.CharField(blank=True, db_column='APELLIDO2_USUARIO', max_length=40, null=True)),
                ('telefono', models.IntegerField(db_column='TELEFONO')),
                ('email', models.CharField(db_column='EMAIL', max_length=40, null=True, unique=True)),
                ('direccion_usuario', models.CharField(db_column='DIRECCION_USUARIO', max_length=80, null=True)),
                ('edad', models.IntegerField(db_column='EDAD')),
                ('password', models.CharField(db_column='CONTRASEÑA', max_length=128)),
                ('es_proveedor', models.BooleanField(db_column='ES_PROVEEDOR', default=False)),
                ('verificado_biometricamente', models.BooleanField(db_column='VERIFICADO_BIOMETRICAMENTE', default=False)),
                ('comuna', models.ForeignKey(db_column='FK_COMUNA', null=True, on_delete=django.db.models.deletion.PROTECT, to='KeyServApp.comuna')),
                ('tipo_cuenta', models.ForeignKey(db_column='FK_TIPO_CUENTA', null=True, on_delete=django.db.models.deletion.PROTECT, to='KeyServApp.tipocuenta')),
                ('transaccion', models.ForeignKey(db_column='FK_TRANSACCION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='KeyServApp.transaccion')),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_valoracion', models.BigAutoField(db_column='ID_VALORACION', primary_key=True, serialize=False)),
                ('puntuacion', models.SmallIntegerField(db_column='PUNTUACION')),
                ('comentario', models.TextField(blank=True, db_column='COMENTARIO', null=True)),
                ('fecha_valoracion', models.DateTimeField(auto_now_add=True, db_column='FECHA_VALORACION')),
                ('publicacion', models.ForeignKey(db_column='FK_PUBLICACION', on_delete=django.db.models.deletion.CASCADE, to='KeyServApp.publicaciones')),
                ('usuario_emisor', models.ForeignKey(db_column='FK_USUARIO_EMISOR', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_emitidas', to='KeyServApp.usuario')),
                ('usuario_receptor', models.ForeignKey(db_column='FK_USUARIO_RECEPTOR', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_recibidas', to='KeyServApp.usuario')),
            ],
            options={
                'db_table': 'VALORACION',
            },
        ),
        migrations.CreateModel(
            name='UsuarioAdministrativo',
            fields=[
                ('id_usuario_administrativo', models.BigAutoField(db_column='ID_USUARIO_ADMINISTRATIVO', primary_key=True, serialize=False)),
                ('rut_usuario_administrativo', models.CharField(db_column='RUT_USUARIO_ADMINISTRATIVO', max_length=10, null=True)),
                ('nombre_usuario_administrativo', models.CharField(db_column='NOMBRE_USUARIO_ADMINISTRATIVO', max_length=40, null=True)),
                ('nombre2_usuario_administrativo', models.CharField(blank=True, db_column='NOMBRE2_USUARIO_ADMINISTRATIVO', max_length=40, null=True)),
                ('apellido_usuario_administrativo', models.CharField(db_column='APELLIDO_USUARIO_ADMINISTRATIVO', max_length=40, null=True)),
                ('apellido2_usuario_administrativo', models.CharField(blank=True, db_column='APELLIDO2_USUARIO_ADMINISTRATIVO', max_length=40, null=True)),
                ('telefono_usuario_administrativo', models.IntegerField(db_column='TELEFONO_USUARIO_ADMINISTRATIVO')),
                ('email_usuario_administrativo', models.CharField(db_column='EMAIL_USUARIO_ADMINISTRATIVO', max_length=40, null=True)),
                ('area_administrativa', models.ForeignKey(db_column='FK_AREA_ADMINISTRATIVA', null=True, on_delete=django.db.models.deletion.PROTECT, to='KeyServApp.areaadministrativa')),
                ('rol_cuenta_administrativa', models.ForeignKey(db_column='FK_ROL_CUENTA_ADMINISTRATIVA', null=True, on_delete=django.db.models.deletion.PROTECT, to='KeyServApp.rolcuentaadministrativa')),
            ],
            options={
                'db_table': 'USUARIO_ADMINISTRATIVO',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id_ranking', models.BigAutoField(db_column='ID_RANKING', primary_key=True, serialize=False)),
                ('total_valoraciones', models.IntegerField(db_column='TOTAL_VALORACIONES', default=0)),
                ('puntuacion_promedio', models.DecimalField(db_column='PUNTUACION_PROMEDIO', decimal_places=2, default=0, max_digits=3)),
                ('usuario', models.OneToOneField(db_column='FK_USUARIO', on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='KeyServApp.usuario')),
            ],
            options={
                'db_table': 'RANKING',
            },
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='usuario_publicador',
            field=models.ForeignKey(db_column='FK_USUARIO_P', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='KeyServApp.usuario'),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.BigAutoField(db_column='ID_MENSAJE', primary_key=True, serialize=False)),
                ('contenido', models.TextField(db_column='CONTENIDO', null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_column='FECHA_ENVIO')),
                ('conversacion', models.ForeignKey(db_column='FK_CONVERSACION', on_delete=django.db.models.deletion.CASCADE, to='KeyServApp.conversacion')),
                ('usuario', models.ForeignKey(db_column='FK_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='KeyServApp.usuario')),
            ],
            options={
                'db_table': 'MENSAJE',
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id_imagen', models.BigAutoField(db_column='ID_IMAGEN', primary_key=True, serialize=False)),
                ('url_imagen', models.TextField(db_column='URL_IMAGEN', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_column='FECHA_SUBIDA')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='ACTUALIZADO_EN')),
                ('publicacion', models.ForeignKey(db_column='FK_PUBLICACION', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='KeyServApp.publicaciones')),
            ],
            options={
                'db_table': 'IMAGENES',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id_gasto', models.BigAutoField(db_column='ID_GASTO', primary_key=True, serialize=False)),
                ('fecha_gasto', models.DateTimeField(auto_now_add=True, db_column='FECHA_GASTO')),
                ('monto_gasto', models.IntegerField(db_column='MONTO_GASTO', null=True)),
                ('responsable_gasto', models.ForeignKey(db_column='FK_RESPONSABLE_GASTO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='KeyServApp.usuarioadministrativo')),
            ],
            options={
                'db_table': 'GASTO',
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id_firma', models.BigAutoField(db_column='ID_FIRMA', primary_key=True, serialize=False)),
                ('hash_firma', models.BinaryField(db_column='HASH_FIRMA', null=True)),
                ('fecha_hora_firma', models.DateTimeField(auto_now_add=True, db_column='FECHA_HORA_FIRMA')),
                ('autentificacion', models.ForeignKey(db_column='FK_AUTENTIFICACION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='KeyServApp.autentificacion')),
                ('documento', models.ForeignKey(db_column='FK_DOCUMENTO', null=True, on_delete=django.db.models.deletion.CASCADE, to='KeyServApp.documento')),
                ('tipo_firma', models.ForeignKey(db_column='FK_TIPO_FIRMA', null=True, on_delete=django.db.models.deletion.PROTECT, to='KeyServApp.tipofirma')),
                ('usuario', models.ForeignKey(db_column='FK_FIRMA_USUARIO', null=True, on_delete=django.db.models.deletion.CASCADE, to='KeyServApp.usuario')),
            ],
            options={
                'db_table': 'FIRMA',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='estado_documento',
            field=models.ForeignKey(db_column='FK_ESTADO_DOCUMENTO', null=True, on_delete=django.db.models.deletion.PROTECT, to='KeyServApp.estadodocumento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(db_column='FK_USUARIO', null=True, on_delete=django.db.models.deletion.CASCADE, to='KeyServApp.usuario'),
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id_contratacion', models.BigAutoField(db_column='ID_CONTRATACION', primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada por el cliente'), ('CONFIRMADA', 'Confirmada por el proveedor'), ('EN_CURSO', 'Servicio en curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], db_column='ESTADO', default='SOLICITADA', max_length=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_CREACION')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_column='FECHA_ACTUALIZACION')),
                ('cliente', models.ForeignKey(db_column='FK_CLIENTE', on_delete=django.db.models.deletion.CASCADE, related_name='contrataciones_como_cliente', to='KeyServApp.usuario')),
                ('proveedor', models.ForeignKey(db_column='FK_PROVEEDOR', on_delete=django.db.models.deletion.CASCADE, related_name='contrataciones_como_proveedor', to='KeyServApp.usuario')),
                ('publicacion', models.ForeignKey(db_column='FK_PUBLICACION', on_delete=django.db.models.deletion.CASCADE, related_name='contrataciones', to='KeyServApp.publicaciones')),
            ],
            options={
                'db_table': 'CONTRATACION',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.BigAutoField(db_column='ID_CONSULTA', primary_key=True, serialize=False)),
                ('asunto_consulta', models.CharField(db_column='ASUNTO_CONSULTA', max_length=120, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True, db_column='FECHA_CONSULTA')),
                ('fecha_termino_consulta', models.DateTimeField(blank=True, db_column='FECHA_TERMINO_CONSULTA', null=True)),
                ('estado_consulta', models.ForeignKey(db_column='FK_ESTADO_CONSULTA', null=True, on_delete=django.db.models.deletion.PROTECT, to='KeyServApp.estadoconsulta')),
                ('usuario_administrativo', models.ForeignKey(db_column='FK_USUARIO_ADMINISTRATIVO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='KeyServApp.usuarioadministrativo')),
                ('usuario_consulta', models.ForeignKey(db_column='FK_USUARIO_CONSULTA', null=True, on_delete=django.db.models.deletion.CASCADE, to='KeyServApp.usuario')),
            ],
            options={
                'db_table': 'CONSULTA',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(db_column='FK_REGION', null=True, on_delete=django.db.models.deletion.PROTECT, to='KeyServApp.region'),
        ),
        migrations.AddField(
            model_name='autentificacion',
            name='estado_autentificacion',
            field=models.ForeignKey(db_column='FK_ESTADO_AUTENTIFICACION', null=True, on_delete=django.db.models.deletion.PROTECT, to='KeyServApp.estadoautentificacion'),
        ),
        migrations.AddField(
            model_name='autentificacion',
            name='usuario',
            field=models.ForeignKey(db_column='FK_USUARIO_AUTENTIFICACION', null=True, on_delete=django.db.models.deletion.CASCADE, to='KeyServApp.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioConversacion',
            fields=[
                ('id_usuario_conversacion', models.BigAutoField(db_column='ID_USUARIO_CONVERSACION', primary_key=True, serialize=False)),
                ('conversacion', models.ForeignKey(db_column='FK_CONVERSACION', on_delete=django.db.models.deletion.CASCADE, to='KeyServApp.conversacion')),
                ('usuario', models.ForeignKey(db_column='FK_USUARIO_C', on_delete=django.db.models.deletion.CASCADE, to='KeyServApp.usuario')),
            ],
            options={
                'db_table': 'USUARIO_CONVERSACION',
                'unique_together': {('usuario', 'conversacion')},
            },
        ),
    ]
