# Generated by Django 4.2.1 on 2023-06-01 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAdministrativa',
            fields=[
                ('ID_AREA_ADMINISTRATIVA', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_AREA_ADMINISTRATIVA', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Autentificacion',
            fields=[
                ('ID_AUTENTIFICACION', models.BigAutoField(primary_key=True, serialize=False)),
                ('CODIGO_AUTENTIFICACION', models.BinaryField(max_length=32, null=True)),
                ('FECHA_AUTENTIFICACION', models.DateTimeField(auto_now_add=True)),
                ('FK_USUARIO_AUTENTIFICACION', models.BigIntegerField(null=True)),
                ('FK_ESTADO_AUTENTIFICACION', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('ID_CONSULTA', models.BigAutoField(primary_key=True, serialize=False)),
                ('ASUNTO_CONSULTA', models.CharField(max_length=120, null=True)),
                ('FECHA_CONSULTA', models.DateTimeField(auto_now_add=True)),
                ('FECHA_TERMINO_CONSULTA', models.DateTimeField(null=True)),
                ('FK_ESTADO_CONSULTA', models.IntegerField(null=True)),
                ('FK_USUARIO_CONSULTA', models.BigIntegerField(null=True)),
                ('FK_USUARIO_ADMINISTRATIVO', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('ID_CONVERSACION', models.BigAutoField(primary_key=True, serialize=False)),
                ('NOMBRE_CONVERSACION', models.CharField(max_length=255, null=True)),
                ('FECHA_CREACION', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('ID_DOCUMENTO', models.BigAutoField(primary_key=True, serialize=False)),
                ('NOMBRE_DOCUMENTO', models.CharField(max_length=60, null=True)),
                ('ARCHIVO', models.BinaryField(null=True)),
                ('FECHA_SUBIDA_DOCUMENTO', models.DateTimeField(auto_now_add=True)),
                ('FK_USUARIO', models.BigIntegerField(null=True)),
                ('FK_ESTADO_DOCUMENTO', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAutentificacion',
            fields=[
                ('ID_ESTADO_AUTENTIFICACION', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_ESTADO_AUTENTIFICACION', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoConsulta',
            fields=[
                ('ID_ESTADO_CONSULTA', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_ESTADO_CONSULTA', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('ID_ESTADO_DOCUMENTO', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_ESTADO_DOCUMENTO', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('ID_FIRMA', models.BigAutoField(primary_key=True, serialize=False)),
                ('HASH_FIRMA', models.BinaryField(max_length=1, null=True)),
                ('FECHA_HORA_FIRMA', models.DateTimeField(auto_now_add=True)),
                ('FK_AUTENTIFICACION', models.BigIntegerField(null=True)),
                ('FK_FIRMA_USUARIO', models.BigIntegerField(null=True)),
                ('FK_TIPO_FIRMA', models.IntegerField(null=True)),
                ('FK_DOCUMENTO', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('ID_GASTO', models.BigAutoField(primary_key=True, serialize=False)),
                ('FECHA_GASTO', models.DateTimeField(auto_now_add=True)),
                ('MONTO_GASTO', models.IntegerField(null=True)),
                ('FK_RESPONSABLE_GASTO', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('ID_IMAGEN', models.BigAutoField(primary_key=True, serialize=False)),
                ('FK_PUBLICACION', models.BigIntegerField(null=True)),
                ('URL_IMAGEN', models.TextField(null=True)),
                ('FECHA_SUBIDA', models.DateTimeField(auto_now_add=True)),
                ('ACTUALIZADO_EN', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('ID_MENSAJE', models.BigAutoField(primary_key=True, serialize=False)),
                ('CONTENIDO', models.TextField(null=True)),
                ('FECHA_ENVIO', models.DateTimeField(auto_now_add=True)),
                ('FK_CONVERSACION', models.BigIntegerField()),
                ('FK_USUARIO', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('ID_PUBLICACION', models.BigAutoField(primary_key=True, serialize=False)),
                ('FK_USUARIO_P', models.BigIntegerField(null=True)),
                ('TITULO', models.CharField(max_length=255, null=True)),
                ('SUB_TITULO', models.CharField(max_length=255, null=True)),
                ('DESCRIPCION_PUBLICACION', models.TextField(null=True)),
                ('FECHA_PUBLICACION', models.DateTimeField(auto_now_add=True)),
                ('ACTUALIZADO_EN', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('ID_RANKING', models.BigAutoField(primary_key=True, serialize=False)),
                ('FK_USUARIO', models.BigIntegerField()),
                ('TOTAL_VALORACIONES', models.IntegerField(default=0)),
                ('PUNTUACION_PROMEDIO', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('ID_REGION', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_REGION', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolCuentaAdministrativa',
            fields=[
                ('ID_ROL_CUENTA_ADMINISTRATIVA', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_ROL_CUENTA_ADMINISTRATIVA', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('ID_TIPO_CUENTA', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_TIPO_CUENTA', models.CharField(max_length=50, null=True)),
                ('VALOR_CUENTA', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFirma',
            fields=[
                ('ID_TIPO_FIRMA', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE_TIPO_FIRMA', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('ID_TRANSACCION', models.BigAutoField(primary_key=True, serialize=False)),
                ('TIEMPO_TRANSACCION', models.DateTimeField(auto_now_add=True)),
                ('FK_VALOR_CUENTA', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_USUARIO', models.BigIntegerField(primary_key=True, serialize=False)),
                ('RUT_USUARIO', models.CharField(max_length=10, null=True)),
                ('NOMBRE_USUARIO', models.CharField(max_length=40, null=True)),
                ('NOMBRE2_USUARIO', models.CharField(max_length=40, null=True)),
                ('APELLIDO_USUARIO', models.CharField(max_length=40, null=True)),
                ('APELLIDO2_USUARIO', models.CharField(max_length=40, null=True)),
                ('TELEFONO', models.IntegerField()),
                ('EMAIL', models.CharField(max_length=40, null=True)),
                ('DIRECCION_USUARIO', models.CharField(max_length=80, null=True)),
                ('FK_TRANSACCION', models.BigIntegerField(null=True)),
                ('FK_TIPO_CUENTA', models.IntegerField(null=True)),
                ('FK_COMUNA', models.IntegerField(null=True)),
                ('EDAD', models.IntegerField()),
                ('CONTRASEÑA', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAdministrativo',
            fields=[
                ('ID_USUARIO_ADMINISTRATIVO', models.IntegerField(primary_key=True, serialize=False)),
                ('RUT_USUARIO_ADMINISTRATIVO', models.CharField(max_length=10, null=True)),
                ('NOMBRE_USUARIO_ADMINISTRATIVO', models.CharField(max_length=40, null=True)),
                ('NOMBRE2_USUARIO_ADMINISTRATIVO', models.CharField(max_length=40, null=True)),
                ('APELLIDO_USUARIO_ADMINISTRATIVO', models.CharField(max_length=40, null=True)),
                ('APELLIDO2_USUARIO_ADMINISTRATIVO', models.CharField(max_length=40, null=True)),
                ('TELEFONO_USUARIO_ADMINISTRATIVO', models.IntegerField()),
                ('EMAIL_USUARIO_ADMINISTRATIVO', models.CharField(max_length=40, null=True)),
                ('FK_ROL_CUENTA_ADMINISTRATIVA', models.IntegerField(null=True)),
                ('FK_AREA_ADMINISTRATIVA', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioConversacion',
            fields=[
                ('ID_USUARIO_CONVERSACION', models.BigIntegerField(primary_key=True, serialize=False)),
                ('FK_USUARIO_C', models.BigIntegerField()),
                ('FK_CONVERSACION', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('ID_VALORACION', models.BigIntegerField(primary_key=True, serialize=False)),
                ('PUNTUACION', models.SmallIntegerField()),
                ('COMENTARIO', models.TextField(null=True)),
                ('FECHA_VALORACION', models.DateTimeField(auto_now_add=True)),
                ('FK_USUARIO_EMISOR', models.BigIntegerField()),
                ('FK_USUARIO_RECEPTOR', models.BigIntegerField()),
                ('FK_PUBLICACION', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_COMUNA', models.CharField(max_length=60)),
                ('FK_REGION', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='KeyServApp.region')),
            ],
        ),
    ]
