# Generated by Django 5.2.16 on 2026-07-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioconversacion',
            name='ultimo_leido',
            field=models.DateTimeField(blank=True, db_column='ULTIMO_LEIDO', null=True),
        ),
    ]
