# Generated by Django 5.2.16 on 2026-07-23 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0002_usuarioconversacion_ultimo_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='contratacion',
            field=models.OneToOneField(blank=True, db_column='FK_CONTRATACION', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversacion', to='KeyServApp.contratacion'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='exportado_en',
            field=models.DateTimeField(blank=True, db_column='EXPORTADO_EN', null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo_subido',
            field=models.FileField(blank=True, db_column='ARCHIVO_SUBIDO', null=True, upload_to='publicaciones/documentos/'),
        ),
        migrations.AddField(
            model_name='documento',
            name='publicacion',
            field=models.ForeignKey(blank=True, db_column='FK_PUBLICACION', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='KeyServApp.publicaciones'),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='archivo',
            field=models.ImageField(blank=True, db_column='ARCHIVO', null=True, upload_to='publicaciones/imagenes/'),
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='categoria',
            field=models.CharField(blank=True, db_column='CATEGORIA', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='url_imagen',
            field=models.TextField(blank=True, db_column='URL_IMAGEN', null=True),
        ),
    ]
