# Generated by Django 5.2.16 on 2026-07-23 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0003_conversacion_contratacion_conversacion_exportado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoContratacion',
            fields=[
                ('id_historial', models.BigAutoField(db_column='ID_HISTORIAL', primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada por el cliente'), ('CONFIRMADA', 'Confirmada por el proveedor'), ('EN_CURSO', 'Servicio en curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], db_column='ESTADO', max_length=12)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='FECHA')),
                ('contratacion', models.ForeignKey(db_column='FK_CONTRATACION', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='KeyServApp.contratacion')),
            ],
            options={
                'db_table': 'HISTORIAL_ESTADO_CONTRATACION',
                'ordering': ['fecha'],
            },
        ),
    ]
