# Generated by Django 5.2.16 on 2026-07-23 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0004_historialestadocontratacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='descripcion',
            field=models.TextField(blank=True, db_column='DESCRIPCION', null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='email_contacto',
            field=models.CharField(blank=True, db_column='EMAIL_CONTACTO', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='nombre_contacto',
            field=models.CharField(blank=True, db_column='NOMBRE_CONTACTO', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='usuario_administrativo',
            field=models.ForeignKey(blank=True, db_column='FK_USUARIO_ADMINISTRATIVO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='KeyServApp.usuarioadministrativo'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='usuario_consulta',
            field=models.ForeignKey(blank=True, db_column='FK_USUARIO_CONSULTA', null=True, on_delete=django.db.models.deletion.CASCADE, to='KeyServApp.usuario'),
        ),
    ]
