# Generated by Django 5.2.16 on 2026-07-23 23:08
"""Siembra el catálogo EstadoConsulta — necesario para que /contacto/ pueda crear una Consulta real (antes el modelo existía pero nunca se usaba, sin datos de catálogo)."""
from django.db import migrations

ESTADOS = [
    (1, 'Abierta'),
    (2, 'En progreso'),
    (3, 'Resuelta'),
    (4, 'Cerrada'),
]


def sembrar(apps, schema_editor):
    EstadoConsulta = apps.get_model('KeyServApp', 'EstadoConsulta')
    for id_estado, nombre in ESTADOS:
        EstadoConsulta.objects.get_or_create(id_estado_consulta=id_estado, defaults={'nombre_estado_consulta': nombre})


def deshacer(apps, schema_editor):
    EstadoConsulta = apps.get_model('KeyServApp', 'EstadoConsulta')
    EstadoConsulta.objects.filter(id_estado_consulta__in=[i for i, _ in ESTADOS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0005_consulta_descripcion_consulta_email_contacto_and_more'),
    ]

    operations = [
        migrations.RunPython(sembrar, deshacer),
    ]
