# Generated by Django 5.2.16 on 2026-07-23 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0006_seed_estado_consulta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, db_column='FK_APROBADO_POR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_moderadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='fecha_moderacion',
            field=models.DateTimeField(blank=True, db_column='FECHA_MODERACION', null=True),
        ),
    ]
