# Generated by Django 5.2.16 on 2026-07-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0007_publicaciones_aprobado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaadministrativa',
            options={'verbose_name': 'Área administrativa', 'verbose_name_plural': 'Áreas administrativas'},
        ),
        migrations.AlterModelOptions(
            name='autentificacion',
            options={'verbose_name': 'Autentificación', 'verbose_name_plural': 'Autentificaciones'},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='contratacion',
            options={'verbose_name': 'Contratación', 'verbose_name_plural': 'Contrataciones'},
        ),
        migrations.AlterModelOptions(
            name='conversacion',
            options={'verbose_name': 'Conversación', 'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='estadoautentificacion',
            options={'verbose_name': 'Estado de autentificación', 'verbose_name_plural': 'Estados de autentificación'},
        ),
        migrations.AlterModelOptions(
            name='estadoconsulta',
            options={'verbose_name': 'Estado de consulta', 'verbose_name_plural': 'Estados de consulta'},
        ),
        migrations.AlterModelOptions(
            name='estadodocumento',
            options={'verbose_name': 'Estado de documento', 'verbose_name_plural': 'Estados de documento'},
        ),
        migrations.AlterModelOptions(
            name='firma',
            options={'verbose_name': 'Firma', 'verbose_name_plural': 'Firmas'},
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='historialestadocontratacion',
            options={'ordering': ['fecha'], 'verbose_name': 'Historial de estado de contratación', 'verbose_name_plural': 'Historial de estados de contratación'},
        ),
        migrations.AlterModelOptions(
            name='imagenes',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='publicaciones',
            options={'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'verbose_name': 'Ranking', 'verbose_name_plural': 'Rankings'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='rolcuentaadministrativa',
            options={'verbose_name': 'Rol de cuenta administrativa', 'verbose_name_plural': 'Roles de cuenta administrativa'},
        ),
        migrations.AlterModelOptions(
            name='tipocuenta',
            options={'verbose_name': 'Tipo de cuenta', 'verbose_name_plural': 'Tipos de cuenta'},
        ),
        migrations.AlterModelOptions(
            name='tipofirma',
            options={'verbose_name': 'Tipo de firma', 'verbose_name_plural': 'Tipos de firma'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuarioadministrativo',
            options={'verbose_name': 'Usuario administrativo', 'verbose_name_plural': 'Usuarios administrativos'},
        ),
        migrations.AlterModelOptions(
            name='usuarioconversacion',
            options={'verbose_name': 'Participante de conversación', 'verbose_name_plural': 'Participantes de conversación'},
        ),
        migrations.AlterModelOptions(
            name='valoracion',
            options={'verbose_name': 'Valoración', 'verbose_name_plural': 'Valoraciones'},
        ),
    ]
