# Generated by Django 5.2.16 on 2026-07-24 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0009_unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='contratacion',
            field=models.OneToOneField(blank=True, db_column='FK_CONTRATACION', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoracion', to='KeyServApp.contratacion'),
        ),
        migrations.CreateModel(
            name='ValoracionImagen',
            fields=[
                ('id_valoracion_imagen', models.BigAutoField(db_column='ID_VALORACION_IMAGEN', primary_key=True, serialize=False)),
                ('archivo', models.ImageField(db_column='ARCHIVO', upload_to='valoraciones/imagenes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_column='FECHA_SUBIDA')),
                ('estado_moderacion', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], db_column='ESTADO_MODERACION', default='PENDIENTE', max_length=10)),
                ('valoracion', models.ForeignKey(db_column='FK_VALORACION', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='KeyServApp.valoracion')),
            ],
            options={
                'verbose_name': 'Imagen de valoración',
                'verbose_name_plural': 'Imágenes de valoración',
                'db_table': 'VALORACION_IMAGEN',
            },
        ),
    ]
