# Generated by Django 5.2.16 on 2026-07-24 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0010_valoracion_contratacion_valoracionimagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, db_column='FK_APROBADO_POR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valoraciones_moderadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='estado_moderacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], db_column='ESTADO_MODERACION', default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='fecha_moderacion',
            field=models.DateTimeField(blank=True, db_column='FECHA_MODERACION', null=True),
        ),
    ]
