# Generated by Django 5.2.16 on 2026-07-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0011_valoracion_aprobado_por_valoracion_estado_moderacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario (cliente/proveedor)', 'verbose_name_plural': 'Usuarios (clientes/proveedores)'},
        ),
    ]
