# Generated by Django 5.2.16 on 2026-07-24 15:32

import KeyServApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0012_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo_subido',
            field=models.FileField(blank=True, db_column='ARCHIVO_SUBIDO', null=True, upload_to='publicaciones/documentos/', validators=[KeyServApp.validators.validar_documento]),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='archivo',
            field=models.ImageField(blank=True, db_column='ARCHIVO', null=True, upload_to='publicaciones/imagenes/', validators=[KeyServApp.validators.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='valoracionimagen',
            name='archivo',
            field=models.ImageField(db_column='ARCHIVO', upload_to='valoraciones/imagenes/', validators=[KeyServApp.validators.validar_imagen]),
        ),
    ]
