# Generated by Django 5.2.16 on 2026-07-24 16:06

import KeyServApp.validators
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0013_alter_documento_archivo_subido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo_subido',
            field=models.FileField(blank=True, db_column='ARCHIVO_SUBIDO', null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('C:/Users/kuity/OneDrive/Escritorio/Felipe/Proyectos/Tesis Mejorada/codigo/backend/django/media_privado')), upload_to='publicaciones/documentos/', validators=[KeyServApp.validators.validar_documento]),
        ),
    ]
