# Generated by Django 5.2.16 on 2026-07-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0014_alter_documento_archivo_subido'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoAccesoSospechoso',
            fields=[
                ('id_intento', models.BigAutoField(db_column='ID_INTENTO', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='FECHA')),
                ('ip', models.GenericIPAddressField(blank=True, db_column='IP', null=True)),
                ('ruta', models.CharField(db_column='RUTA', max_length=255)),
                ('recurso', models.CharField(db_column='RECURSO', max_length=40)),
                ('recurso_id', models.CharField(blank=True, db_column='RECURSO_ID', max_length=40, null=True)),
                ('detalle', models.CharField(blank=True, db_column='DETALLE', max_length=255, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='FK_USUARIO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='KeyServApp.usuario')),
            ],
            options={
                'verbose_name': 'Intento de acceso sospechoso',
                'verbose_name_plural': 'Intentos de acceso sospechoso',
                'db_table': 'INTENTO_ACCESO_SOSPECHOSO',
                'ordering': ['-fecha'],
            },
        ),
    ]
