# Generated by Django 5.2.16 on 2026-07-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0015_intentoaccesosospechoso'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoaccesosospechoso',
            name='ciudad',
            field=models.CharField(blank=True, db_column='CIUDAD', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='intentoaccesosospechoso',
            name='pais',
            field=models.CharField(blank=True, db_column='PAIS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='intentoaccesosospechoso',
            name='user_agent',
            field=models.CharField(blank=True, db_column='USER_AGENT', max_length=255, null=True),
        ),
    ]
