# Generated by Django 5.2.16 on 2026-07-24 19:05

import KeyServApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0016_intentoaccesosospechoso_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, db_column='FOTO_PERFIL', null=True, upload_to='perfiles/', validators=[KeyServApp.validators.validar_imagen]),
        ),
    ]
