# Generated by Django 5.2.16 on 2026-07-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0017_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='precio',
            field=models.PositiveIntegerField(blank=True, db_column='PRECIO', null=True),
        ),
    ]
