# Generated by Django 5.2.16 on 2026-07-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0018_publicaciones_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigAutoField(db_column='ID_PAGO', primary_key=True, serialize=False)),
                ('monto', models.PositiveIntegerField(db_column='MONTO')),
                ('metodo', models.CharField(choices=[('WEBPAY', 'Webpay Plus'), ('KHIPU', 'Khipu')], db_column='METODO', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado/cancelado')], db_column='ESTADO', default='PENDIENTE', max_length=10)),
                ('orden_compra', models.CharField(blank=True, db_column='ORDEN_COMPRA', max_length=26, null=True)),
                ('token_webpay', models.CharField(blank=True, db_column='TOKEN_WEBPAY', max_length=64, null=True)),
                ('khipu_payment_id', models.CharField(blank=True, db_column='KHIPU_PAYMENT_ID', max_length=64, null=True)),
                ('respuesta_bruta', models.JSONField(blank=True, db_column='RESPUESTA_BRUTA', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FECHA_CREACION')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, db_column='FECHA_CONFIRMACION', null=True)),
                ('contratacion', models.OneToOneField(db_column='FK_CONTRATACION', on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='KeyServApp.contratacion')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'PAGO',
            },
        ),
    ]
