# Generated by Django 5.2.16 on 2026-07-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0019_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='monto_acordado',
            field=models.PositiveIntegerField(blank=True, db_column='MONTO_ACORDADO', null=True),
        ),
    ]
