# Generated by Django 5.2.16 on 2026-07-24 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0020_contratacion_monto_acordado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id_item_presupuesto', models.BigAutoField(db_column='ID_ITEM_PRESUPUESTO', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='DESCRIPCION', max_length=200)),
                ('categoria', models.CharField(choices=[('MATERIAL', 'Materiales'), ('MANO_DE_OBRA', 'Tiempo y esfuerzo'), ('VIAJE', 'Gasto de viaje'), ('OTRO', 'Otro')], db_column='CATEGORIA', default='OTRO', max_length=12)),
                ('monto', models.PositiveIntegerField(db_column='MONTO')),
                ('orden', models.PositiveSmallIntegerField(db_column='ORDEN', default=0)),
                ('contratacion', models.ForeignKey(db_column='FK_CONTRATACION', on_delete=django.db.models.deletion.CASCADE, related_name='items_presupuesto', to='KeyServApp.contratacion')),
            ],
            options={
                'verbose_name': 'Ítem de presupuesto',
                'verbose_name_plural': 'Ítems de presupuesto',
                'db_table': 'ITEM_PRESUPUESTO',
                'ordering': ['orden', 'id_item_presupuesto'],
            },
        ),
    ]
