# Generated by Django 5.2.16 on 2026-07-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0021_itempresupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='areas_servicio',
            field=models.CharField(blank=True, db_column='AREAS_SERVICIO', max_length=300),
        ),
        migrations.AddField(
            model_name='usuario',
            name='experiencia',
            field=models.TextField(blank=True, db_column='EXPERIENCIA'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificaciones_sonido',
            field=models.BooleanField(db_column='NOTIFICACIONES_SONIDO', default=True),
        ),
    ]
