# Generated by Django 5.2.16 on 2026-07-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0023_alter_documento_archivo_subido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='encoding_facial',
            field=models.JSONField(blank=True, db_column='ENCODING_FACIAL', null=True),
        ),
    ]
