# Generated by Django 5.2.16 on 2026-08-13 23:12

import KeyServApp.validators
import django.core.files.storage
import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0024_usuario_encoding_facial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo_subido',
            field=models.FileField(blank=True, db_column='ARCHIVO_SUBIDO', null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('C:/Users/kuity/OneDrive/Escritorio/Felipe/Proyectos/Tesis Mejorada/codigo/backend/django/media_privado')), upload_to='publicaciones/documentos/', validators=[KeyServApp.validators.validar_documento]),
        ),
        migrations.CreateModel(
            name='TokenSesion',
            fields=[
                ('id_token_sesion', models.BigAutoField(db_column='ID_TOKEN_SESION', primary_key=True, serialize=False)),
                ('refresh_token_hash', models.CharField(db_column='REFRESH_TOKEN_HASH', max_length=128, unique=True)),
                ('dispositivo', models.CharField(blank=True, db_column='DISPOSITIVO', max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='CREADO_EN')),
                ('expira_en', models.DateTimeField(db_column='EXPIRA_EN')),
                ('revocado_en', models.DateTimeField(blank=True, db_column='REVOCADO_EN', null=True)),
                ('usuario', models.ForeignKey(db_column='FK_USUARIO', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_sesion', to='KeyServApp.usuario')),
            ],
            options={
                'verbose_name': 'Token de sesión',
                'verbose_name_plural': 'Tokens de sesión',
                'db_table': 'TOKEN_SESION',
                'ordering': ['-creado_en'],
            },
        ),
    ]
