# Generated by Django 5.2.16 on 2026-08-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0025_alter_documento_archivo_subido_tokensesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='latitud',
            field=models.DecimalField(blank=True, db_column='LATITUD', decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='comuna',
            name='longitud',
            field=models.DecimalField(blank=True, db_column='LONGITUD', decimal_places=6, max_digits=9, null=True),
        ),
    ]
