# Generated by Django 5.2.16 on 2026-08-16 17:31

from django.db import migrations

# Coordenadas aproximadas de la plaza principal / centro cívico de cada
# comuna — solo las 9 comunas de la Región Metropolitana usadas por los
# datos demo sembrados (ver docs/BACKLOG.md, "Búsqueda por geolocalización").
# Son de conocimiento general, no de un geocoder verificado en vivo: alcanzan
# para probar el filtro de radio de punta a punta, no para producción real.
# El resto de las ~330 comunas queda con latitud/longitud NULL hasta que se
# geocodifiquen — no se completan todas de una — y no se corrige esta lista
# in-place más adelante: cualquier ajuste futuro va en una migración nueva.
COORDENADAS_PLAZA_PRINCIPAL = {
    1: ('-33.437700', '-70.650500'),   # Santiago (Plaza de Armas)
    6: ('-33.459300', '-70.686000'),   # Estación Central
    10: ('-33.524900', '-70.598000'),  # La Florida
    14: ('-33.409800', '-70.569500'),  # Las Condes
    19: ('-33.510800', '-70.757800'),  # Maipú (Plaza de Maipú)
    20: ('-33.455800', '-70.598000'),  # Ñuñoa (Plaza Ñuñoa)
    25: ('-33.423700', '-70.611200'),  # Providencia
    27: ('-33.611000', '-70.575700'),  # Puente Alto
    32: ('-33.592800', '-70.700300'),  # San Bernardo (Plaza de Armas)
}


def cargar_coordenadas(apps, schema_editor):
    Comuna = apps.get_model('KeyServApp', 'Comuna')
    for id_comuna, (latitud, longitud) in COORDENADAS_PLAZA_PRINCIPAL.items():
        Comuna.objects.filter(pk=id_comuna).update(latitud=latitud, longitud=longitud)


def revertir_coordenadas(apps, schema_editor):
    Comuna = apps.get_model('KeyServApp', 'Comuna')
    Comuna.objects.filter(pk__in=COORDENADAS_PLAZA_PRINCIPAL.keys()).update(latitud=None, longitud=None)


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0026_comuna_latitud_longitud'),
    ]

    operations = [
        migrations.RunPython(cargar_coordenadas, revertir_coordenadas),
    ]
