# Generated by Django 5.2.16 on 2026-08-16 21:11

import KeyServApp.validators
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KeyServApp', '0027_comuna_coordenadas_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='imagen',
            field=models.ImageField(blank=True, db_column='IMAGEN', null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('C:/Users/kuity/OneDrive/Escritorio/Felipe/Proyectos/Tesis Mejorada/codigo/backend/django/media_privado')), upload_to='mensajes/imagenes/', validators=[KeyServApp.validators.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.TextField(blank=True, db_column='CONTENIDO', null=True),
        ),
    ]
