from django.urls import path

from . import views

app_name = 'KeyServApp_api'

urlpatterns = [
    path('auth/login/', views.LoginView.as_view(), name='login'),
    path('auth/registro/', views.RegistroView.as_view(), name='registro'),
    path('contacto/', views.ContactoView.as_view(), name='contacto'),
    path('auth/me/', views.MeView.as_view(), name='me'),
    path('auth/perfil/', views.PerfilView.as_view(), name='perfil'),
    path('auth/alternar-proveedor/', views.AlternarProveedorView.as_view(), name='alternar-proveedor'),
    path('perfil/resenas-recibidas/', views.ResenasRecibidasView.as_view(), name='resenas-recibidas'),
    path('auth/verificar-biometria-nativa/', views.VerificarBiometriaNativaView.as_view(), name='verificar-biometria-nativa'),
    path('auth/rostro/estado/', views.RostroEstadoView.as_view(), name='rostro-estado'),
    path('auth/rostro/registrar/', views.RostroRegistrarView.as_view(), name='rostro-registrar'),
    path('auth/rostro/verificar/', views.RostroVerificarView.as_view(), name='rostro-verificar'),
    path('auth/perfil-proveedor/', views.PerfilProveedorView.as_view(), name='perfil-proveedor'),
    path('auth/perfil-proveedor/documentos/', views.DocumentoPerfilListView.as_view(), name='perfil-proveedor-documentos'),
    path('auth/perfil-proveedor/documentos/<int:documento_id>/', views.DocumentoPerfilEliminarView.as_view(), name='perfil-proveedor-documento-eliminar'),
    path('auth/preferencias/', views.PreferenciasView.as_view(), name='preferencias'),
    path('auth/cambiar-password/', views.CambiarPasswordView.as_view(), name='cambiar-password'),
    path('auth/recuperar/', views.RecuperarView.as_view(), name='recuperar'),
    path('auth/recuperar/confirmar/<str:token>/', views.RecuperarConfirmarView.as_view(), name='recuperar-confirmar'),
    path('publicaciones/', views.PublicacionListView.as_view(), name='publicaciones-list'),
    path('publicaciones/crear/', views.PublicacionCrearView.as_view(), name='publicaciones-crear'),
    path('publicaciones/mias/', views.MisPublicacionesView.as_view(), name='publicaciones-mias'),
    path('publicaciones/<int:pk>/', views.PublicacionDetailView.as_view(), name='publicaciones-detail'),
    path('conversaciones/', views.ConversacionListView.as_view(), name='conversaciones-list'),
    path('contrataciones/', views.ContratacionListCreateView.as_view(), name='contrataciones-list'),
    path('contrataciones/<int:contratacion_id>/', views.ContratacionDetailView.as_view(), name='contrataciones-detail'),
    path('contrataciones/<int:contratacion_id>/mensajes/', views.ContratacionMensajesView.as_view(), name='contrataciones-mensajes'),
    path('contrataciones/<int:contratacion_id>/confirmar/', views.ContratacionConfirmarView.as_view(), name='contrataciones-confirmar'),
    path('contrataciones/<int:contratacion_id>/completar/', views.ContratacionCompletarView.as_view(), name='contrataciones-completar'),
    path('contrataciones/<int:contratacion_id>/valoracion/', views.ValoracionCrearView.as_view(), name='contrataciones-valoracion'),
    path('contrataciones/<int:contratacion_id>/pagos/webpay/iniciar/', views.PagoWebpayIniciarView.as_view(), name='pagos-webpay-iniciar'),
    path('pagos/webpay/confirmar/', views.PagoWebpayConfirmarView.as_view(), name='pagos-webpay-confirmar'),
    path('contrataciones/<int:contratacion_id>/pagos/khipu/iniciar/', views.PagoKhipuIniciarView.as_view(), name='pagos-khipu-iniciar'),
    path('contrataciones/<int:contratacion_id>/pagos/khipu/estado/', views.PagoKhipuEstadoView.as_view(), name='pagos-khipu-estado'),
    path('pagos/historial/', views.PagoHistorialView.as_view(), name='pagos-historial'),
    path('catalogos/regiones/', views.RegionListView.as_view(), name='catalogo-regiones'),
    path('catalogos/comunas/', views.ComunaListView.as_view(), name='catalogo-comunas'),
    path('catalogos/tipos-cuenta/', views.TipoCuentaListView.as_view(), name='catalogo-tipos-cuenta'),
    path('catalogos/categorias/', views.CategoriasListView.as_view(), name='catalogo-categorias'),
]
